#!/usr/bin/env python3
"""cff_stdenc.py — the CFF Standard Encoding, and what rekha checks itself against.

    python3 scripts/cff_stdenc.py emit   [out.cyr]   # write programs/cff_stdenc_vectors.cyr
    python3 scripts/cff_stdenc.py verify             # cross-check the table against fontTools

WHY THIS EXISTS. A CFF `seac` (the four-argument `endchar`) names its base and accent glyphs by
STANDARD ENCODING CODE, not by glyph id. src/cff.cyr turns a code into an SID with fourteen
contiguous ranges rather than a 256-entry literal, because the table happens to be almost entirely
runs — and a wrong range picks the wrong accent silently, which is the failure mode a font parser
can least afford.

So `emit` writes programs/cff_stdenc_vectors.cyr — all 256 codes and the SID each one means, taken
from the table below and from nothing in rekha — and CI requires the committed file to equal a
fresh emit, exactly as it does for programs/woff2_vectors.cyr and fonts/face_data.cyr.

`verify` re-derives the same table from **fontTools** (`encodings.StandardEncoding` composed with
`cffLib.cffStandardStrings`) and requires a byte-equal match, so the transcription can be re-audited
against an independent implementation. fontTools is NOT a dependency of this repo and CI does not
run that mode.

THE TABLE. `code<TAB>SID`, 256 rows. SID 0 is .notdef, which is also what an unassigned code means.
Verified against fontTools 4.65.0 on 2026-09-20: 149 assigned codes, codes 32..126 running to SIDs
1..95 contiguously.
"""
import sys

STD_ENCODING = """\
0	0
1	0
2	0
3	0
4	0
5	0
6	0
7	0
8	0
9	0
10	0
11	0
12	0
13	0
14	0
15	0
16	0
17	0
18	0
19	0
20	0
21	0
22	0
23	0
24	0
25	0
26	0
27	0
28	0
29	0
30	0
31	0
32	1
33	2
34	3
35	4
36	5
37	6
38	7
39	8
40	9
41	10
42	11
43	12
44	13
45	14
46	15
47	16
48	17
49	18
50	19
51	20
52	21
53	22
54	23
55	24
56	25
57	26
58	27
59	28
60	29
61	30
62	31
63	32
64	33
65	34
66	35
67	36
68	37
69	38
70	39
71	40
72	41
73	42
74	43
75	44
76	45
77	46
78	47
79	48
80	49
81	50
82	51
83	52
84	53
85	54
86	55
87	56
88	57
89	58
90	59
91	60
92	61
93	62
94	63
95	64
96	65
97	66
98	67
99	68
100	69
101	70
102	71
103	72
104	73
105	74
106	75
107	76
108	77
109	78
110	79
111	80
112	81
113	82
114	83
115	84
116	85
117	86
118	87
119	88
120	89
121	90
122	91
123	92
124	93
125	94
126	95
127	0
128	0
129	0
130	0
131	0
132	0
133	0
134	0
135	0
136	0
137	0
138	0
139	0
140	0
141	0
142	0
143	0
144	0
145	0
146	0
147	0
148	0
149	0
150	0
151	0
152	0
153	0
154	0
155	0
156	0
157	0
158	0
159	0
160	0
161	96
162	97
163	98
164	99
165	100
166	101
167	102
168	103
169	104
170	105
171	106
172	107
173	108
174	109
175	110
176	0
177	111
178	112
179	113
180	114
181	0
182	115
183	116
184	117
185	118
186	119
187	120
188	121
189	122
190	0
191	123
192	0
193	124
194	125
195	126
196	127
197	128
198	129
199	130
200	131
201	0
202	132
203	133
204	0
205	134
206	135
207	136
208	137
209	0
210	0
211	0
212	0
213	0
214	0
215	0
216	0
217	0
218	0
219	0
220	0
221	0
222	0
223	0
224	0
225	138
226	0
227	139
228	0
229	0
230	0
231	0
232	140
233	141
234	142
235	143
236	0
237	0
238	0
239	0
240	0
241	144
242	0
243	0
244	0
245	145
246	0
247	0
248	146
249	147
250	148
251	149
252	0
253	0
254	0
255	0"""


def table():
    out = []
    for line in STD_ENCODING.strip().split("\n"):
        c, s = line.split("\t")
        assert int(c) == len(out), line
        out.append(int(s))
    assert len(out) == 256, len(out)
    return out


def emit(path):
    tab = table()
    src = [
        "# programs/cff_stdenc_vectors.cyr — GENERATED by scripts/cff_stdenc.py. DO NOT EDIT.",
        "#",
        "# The CFF Standard Encoding as 256 (code, SID) pairs: what a `seac`'s bchar and achar mean.",
        "# Nothing here is derived from src/cff.cyr — that is the point, since the decoder expresses",
        "# the same table as fourteen arithmetic ranges. CI requires this file to equal a fresh",
        "# `python3 scripts/cff_stdenc.py emit`.",
        "",
        "var REKHA_STDENC_N = 256;",
        "",
        "# Fill `p` with 256 i64 SIDs, indexed by code.",
        "fn cff_stdenc_fill(p): i64 {",
    ]
    # one statement per line: the 120-column lint refuses the packed form, and the formatter
    # is stable on this one (both checked).
    for code, sid in enumerate(tab):
        src.append("    store64(p + %d, %d);" % (code * 8, sid))
    src += ["    return 0;", "}", ""]
    open(path, "w").write("\n".join(src))
    print("wrote %s (256 codes, %d assigned)" % (path, sum(1 for v in tab if v)))


def verify():
    try:
        from fontTools.encodings.StandardEncoding import StandardEncoding
        from fontTools.cffLib import cffStandardStrings
    except ImportError:
        print("fontTools is not installed; `verify` needs it. (CI does not run this mode.)")
        return 2
    sid = {n: i for i, n in enumerate(cffStandardStrings)}
    got = []
    for code in range(256):
        n = StandardEncoding[code] if code < len(StandardEncoding) else None
        got.append(sid.get(n, 0) if n and n != ".notdef" else 0)
    want = table()
    bad = [(c, w, g) for c, (w, g) in enumerate(zip(want, got)) if w != g]
    if bad:
        for c, w, g in bad[:10]:
            print("code %d: embedded SID %d != fontTools %d" % (c, w, g))
        print("MISMATCH in %d of 256 codes" % len(bad))
        return 1
    print("the embedded table matches fontTools exactly: all 256 codes, %d assigned"
          % sum(1 for v in want if v))
    return 0


if __name__ == "__main__":
    if len(sys.argv) >= 2 and sys.argv[1] == "emit":
        emit(sys.argv[2] if len(sys.argv) > 2 else "programs/cff_stdenc_vectors.cyr")
    elif len(sys.argv) == 2 and sys.argv[1] == "verify":
        sys.exit(verify())
    else:
        print(__doc__)
        sys.exit(2)
