#!/usr/bin/env python3
"""face2cyr — emit a FREESTANDING Cyrius module carrying one TrueType face as data.

    python3 scripts/face2cyr.py fonts/LiberationSans-Regular.ttf fonts/face_data.cyr

The output uses NO stdlib, NO heap, NO syscalls — only string literals, integer arithmetic and
the load8/store8 intrinsics — so a freestanding kernel (agnos: `[deps] stdlib = []`) can
`include`/concatenate it exactly the way it consumes kashi's src/font_data.cyr.

⛔ WHY 4096-BYTE CHUNKS, MEASURED (cyrius 6.6.3, 2026-09-13): a string literal of EVEN length
>= 65536 is emitted SHIFTED BY ONE BYTE (its first byte lost) on every alternate literal —
rc=0, byte COUNT intact, only the CONTENT wrong. Odd lengths >= 65536 and every length below
65536 came out byte-exact (bisected over 4096..131072 against an FNV-1a of the source file).
Filed against cyrius. Chunks stay far below the trap, and the module carries the FNV-1a of the
whole face so a consumer verifies the bytes it assembled instead of trusting the compiler.
Python stdlib only — no fonttools. The face is embedded UNMODIFIED (no subsetting), which is
what keeps an OFL face's Reserved Font Name intact; see fonts/LICENSE-LiberationFonts.
"""
import hashlib
import os
import struct
import sys

CHUNK = 4096
FNV_OFFSET = 0xcbf29ce484222325
FNV_PRIME = 0x100000001b3
MASK = (1 << 64) - 1


def fnv1a(data):
    h = FNV_OFFSET
    for b in data:
        h = ((h ^ b) * FNV_PRIME) & MASK
    return h


def sfnt_summary(data):
    """(sfntVersion, numTables, tags) — enough to refuse a CFF face up front."""
    ver, num = struct.unpack('>IH', data[:6])
    tags = [data[12 + 16 * i:16 + 16 * i].decode('latin-1') for i in range(num)]
    return ver, num, tags


def main():
    if len(sys.argv) != 3:
        sys.stderr.write(__doc__)
        return 2
    src, out = sys.argv[1], sys.argv[2]
    data = open(src, 'rb').read()
    n = len(data)
    ver, num, tags = sfnt_summary(data)
    if ver not in (0x00010000, 0x74727565):          # 0x00010000 / 'true' — glyf outlines only
        sys.stderr.write('refusing %s: sfntVersion 0x%08x is not a glyf face (rekha rejects CFF)\n' % (src, ver))
        return 1
    for need in ('glyf', 'loca', 'cmap', 'hhea', 'hmtx', 'head', 'maxp'):
        if need not in tags:
            sys.stderr.write('refusing %s: no %r table\n' % (src, need))
            return 1
    chunks = [data[i:i + CHUNK] for i in range(0, n, CHUNK)]
    h = fnv1a(data)
    sha = hashlib.sha256(data).hexdigest()
    name = os.path.basename(src)
    with open(out, 'w') as f:
        w = f.write
        w('# === rekha — freestanding default-face data (GENERATED, do not hand-edit) ===\n')
        w('#\n')
        w('# Generated by scripts/face2cyr.py from fonts/%s\n' % name)
        w('#   %d bytes · sha256 %s\n' % (n, sha))
        w('#   sfntVersion 0x%08x · %d tables: %s\n' % (ver, num, ' '.join(tags)))
        w('#   FNV-1a-64 of the whole face: 0x%016x\n' % h)
        w('#\n')
        w('# THIS FILE IS FREESTANDING. It uses NO stdlib, NO heap, NO syscalls — only string\n')
        w('# literals, integer arithmetic and the load8/store8 intrinsics — so a freestanding\n')
        w('# kernel (agnos: `[deps] stdlib = []`, vendored klib/) can concatenate it exactly as it\n')
        w('# consumes kashi\'s src/font_data.cyr. Do NOT add includes here.\n')
        w('#\n')
        w('# The face is embedded UNMODIFIED and licensed under the SIL Open Font License 1.1 —\n')
        w('# Copyright (c) 2012 Red Hat, Inc., with Reserved Font Name Liberation; digitized data\n')
        w('# copyright (c) 2010 Google Corporation. The licence text ships next to the source face\n')
        w('# as fonts/LICENSE-LiberationFonts and MUST travel with any redistribution of these bytes.\n')
        w('# rekha itself is GPL-3.0-only; the OFL permits bundling with software under any licence.\n')
        w('#\n')
        w('# Storage model: %d string literals of %d bytes (the tail shorter), reachable by index\n' % (len(chunks), CHUNK))
        w('# through rekha_face_default_chunk(i). ⛔ 4 KB ON PURPOSE — cyrius 6.6.3 emits a string\n')
        w('# literal of EVEN length >= 65536 shifted by one byte on every alternate literal, silently\n')
        w('# (rc=0, count intact, content wrong); measured by bisection, filed against cyrius. A\n')
        w('# consumer assembles the chunks into ONE contiguous buffer with rekha_face_default_copy()\n')
        w('# and MUST check rekha_face_default_verify() before exposing the result to anyone.\n')
        w('#\n')
        w('# Consumption contract (agnos kernel):\n')
        w('#   var n = rekha_face_default_len();\n')
        w('#   rekha_face_default_copy(dst, cap)        -> n, or -1 when cap < n\n')
        w('#   rekha_face_default_verify(dst, n)        -> 1 when FNV-1a matches, else 0\n')
        w('#   rekha_face_default_name() / _name_len()  -> the source filename\n')
        w('\n')
        w('fn rekha_face_default_len() { return %d; }\n' % n)
        w('fn rekha_face_default_chunk_size() { return %d; }\n' % CHUNK)
        w('fn rekha_face_default_chunk_count() { return %d; }\n' % len(chunks))
        w('fn rekha_face_default_fnv1a() { return 0x%016x; }\n' % h)
        w('fn rekha_face_default_name() { return "%s"; }\n' % name)
        w('fn rekha_face_default_name_len() { return %d; }\n' % len(name))
        w('\n')
        w('# Byte length of chunk i (every chunk is full-size except the last).\n')
        w('fn rekha_face_default_chunk_len(i) {\n')
        w('    if (i < 0) { return 0; }\n')
        w('    if (i >= %d) { return 0; }\n' % len(chunks))
        w('    if (i == %d) { return %d; }\n' % (len(chunks) - 1, len(chunks[-1])))
        w('    return %d;\n' % CHUNK)
        w('}\n')
        w('\n')
        w('# Copy the whole face into dst (cap bytes). Returns the face length, or -1 if cap is too small.\n')
        w('fn rekha_face_default_copy(dst, cap) {\n')
        w('    var n = rekha_face_default_len();\n')
        w('    if (cap < n) { return 0 - 1; }\n')
        w('    var i = 0;\n')
        w('    var off = 0;\n')
        w('    while (i < rekha_face_default_chunk_count()) {\n')
        w('        var p = rekha_face_default_chunk(i);\n')
        w('        var l = rekha_face_default_chunk_len(i);\n')
        w('        var j = 0;\n')
        w('        while (j < l) { store8(dst + off + j, load8(p + j)); j = j + 1; }\n')
        w('        off = off + l;\n')
        w('        i = i + 1;\n')
        w('    }\n')
        w('    return off;\n')
        w('}\n')
        w('\n')
        w('# FNV-1a-64 over buf[0..len) compared to the generator\'s hash of the source file.\n')
        w('# 1 = the bytes are the face, byte-exact; 0 = do not expose them.\n')
        w('fn rekha_face_default_verify(buf, len) {\n')
        w('    if (len != rekha_face_default_len()) { return 0; }\n')
        w('    var h = 0x%016x;\n' % FNV_OFFSET)
        w('    var j = 0;\n')
        w('    while (j < len) { h = (h ^ load8(buf + j)) * 0x%x; j = j + 1; }\n' % FNV_PRIME)
        w('    if (h == rekha_face_default_fnv1a()) { return 1; }\n')
        w('    return 0;\n')
        w('}\n')
        w('\n')
        w('# Pointer to chunk i\'s bytes (a string literal in .rodata; NOT NUL-safe — use the length).\n')
        w('fn rekha_face_default_chunk(i) {\n')
        for i, c in enumerate(chunks):
            w('    if (i == %d) { return "%s"; }\n' % (i, ''.join('\\x%02x' % b for b in c)))
        w('    return 0;\n')
        w('}\n')
    print('%s: %d bytes, %d chunks, fnv1a 0x%016x, sha256 %s' % (out, n, len(chunks), h, sha))
    return 0


if __name__ == '__main__':
    sys.exit(main())
