#!/usr/bin/env python3
"""gpos_kern_diff.py — GPOS pair kerning against fontTools, on every font on this machine.

    python3 scripts/gpos_kern_diff.py [--fonts N] [dir ...]   # needs fontTools

For each font with a GPOS `kern` feature it picks a glyph sample — glyphs that appear in a PairPos
coverage, plus some that do not — and asks both implementations for **every ordered pair** of that
sample. So hits and misses are both covered by construction, and a lookup that returns a
neighbouring entry fails on the misses even when every hit is right.

⚠ WHAT THE REFERENCE IS. fontTools DECOMPILES GPOS into an object model — Coverage, ClassDef,
PairPos, ValueRecords with their bitfield sizing — and that decompiler is a thorough, independent
implementation of the byte-level parse. That is the half this settles. It does not decide which
lookups a `(left, right)` query should consult, so the feature-union / dedup / accumulate /
first-subtable-wins rule is rekha's, and this script models it.

⛔ A DEV-HOST DIFFERENTIAL, like scripts/kern_diff.py and rekha's CFF and WOFF2 sweeps: it reads
the machine's installed fonts, which are not in this repo. Run it and record the counts.

⛔ Compiles and runs a throwaway Cyrius program under build/ (gitignored). Run from the repo root.
"""
import glob
import os
import random
import struct
import subprocess
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO, "build")
DIRS = ["/usr/share/fonts", os.path.expanduser("~/.local/share/fonts"),
        os.path.expanduser("~/.fonts")]
SAMPLE = 90            # glyphs per font; the pair count is its square
MAX_FONTS = 40

DUMPER = r'''# GENERATED by scripts/gpos_kern_diff.py — throwaway, under build/.
include "programs/prelude.cyr"

fn main(): i64 {
    alloc_init();
    var cap = 67108864;
    var buf = alloc(cap);
    var n = file_read_all("__FONT__", buf, cap);
    if (n <= 0) { syscall(1, 2, "read failed\n", 12); return 1; }
    var f = rekha_font_open(buf, n);
    if (f == 0) { syscall(1, 1, "NOFONT\n", 7); return 0; }
    var pcap = 33554432;
    var pb = alloc(pcap);
    if (file_read_all("__PAIRS__", pb, pcap) < 8) { syscall(1, 2, "pairs\n", 6); return 1; }
    var np = load64(pb);
    var i = 0;
    while (i < np) {
        fmt_int(rekha_gpos_kern_pair(f, load64(pb + 8 + i * 16), load64(pb + 16 + i * 16)));
        syscall(1, 1, "\n", 1);
        i = i + 1;
    }
    return 0;
}

var exit_code = main();
syscall(60, exit_code);
'''


def kern_lookups(gpos):
    """Every lookup behind a `kern` feature, deduplicated, in first-seen order."""
    out, seen = [], set()
    fl = gpos.FeatureList
    ll = gpos.LookupList
    if fl is None or ll is None:
        return out
    for rec in fl.FeatureRecord:
        if rec.FeatureTag != "kern":
            continue
        for li in rec.Feature.LookupListIndex:
            if 0 <= li < len(ll.Lookup) and li not in seen:
                seen.add(li)
                out.append(ll.Lookup[li])
    return out


def subtables(lk):
    """The pair-positioning subtables of a lookup, unwrapping extensions."""
    out = []
    for st in lk.SubTable:
        if lk.LookupType == 9:
            if getattr(st, "ExtensionLookupType", None) == 2:
                out.append(st.ExtSubTable)
            else:
                out.append(None)          # a subtable rekha skips, but it still occupies a slot
        elif lk.LookupType == 2:
            out.append(st)
        else:
            out.append(None)
    return out


def xadv(v):
    return 0 if v is None else getattr(v, "XAdvance", 0) or 0


def sub_value(st, a, b):
    """(matched, value) for one PairPos subtable."""
    if st is None:
        return (False, 0)
    cov = set(st.Coverage.glyphs)
    if a not in cov:
        return (False, 0)
    if st.Format == 1:
        i = st.Coverage.glyphs.index(a)
        if i >= len(st.PairSet):
            return (False, 0)
        for rec in st.PairSet[i].PairValueRecord:
            if rec.SecondGlyph == b:
                return (True, xadv(rec.Value1))
        return (False, 0)
    if st.Format == 2:
        c1 = st.ClassDef1.classDefs.get(a, 0)
        c2 = st.ClassDef2.classDefs.get(b, 0)
        if c1 >= st.Class1Count or c2 >= st.Class2Count:
            return (False, 0)
        rec = st.Class1Record[c1].Class2Record[c2]
        return (True, xadv(rec.Value1))
    return (False, 0)


def reference(lookups, a, b):
    """rekha's rule: accumulate across lookups, first matching subtable wins inside one."""
    total = 0
    for lk in lookups:
        for st in subtables(lk):
            hit, v = sub_value(st, a, b)
            if hit:
                total += v
                break
    return total


def rekha_values(path, pairs):
    open(os.path.join(OUT, "gkd.cyr"), "w").write(
        DUMPER.replace("__FONT__", path).replace("__PAIRS__", os.path.join(OUT, "gkd.pairs")))
    blob = struct.pack("<q", len(pairs))
    for a, b in pairs:
        blob += struct.pack("<qq", a, b)
    open(os.path.join(OUT, "gkd.pairs"), "wb").write(blob)
    r = subprocess.run(["cyrius", "build", "build/gkd.cyr", "build/gkd"],
                       cwd=REPO, capture_output=True, text=True)
    if r.returncode != 0:
        print(r.stdout, r.stderr)
        sys.exit("dumper build failed")
    r = subprocess.run([os.path.join(OUT, "gkd")], capture_output=True, text=True)
    if r.returncode != 0:
        sys.exit("dumper run failed: " + r.stderr)
    if r.stdout.startswith("NOFONT"):
        return None
    return [int(x) for x in r.stdout.split()]


def main(argv):
    from fontTools.ttLib import TTFont
    args = [a for a in argv[1:] if not a.startswith("--")]
    maxf = MAX_FONTS
    if "--fonts" in argv:
        maxf = int(argv[argv.index("--fonts") + 1])
        args = [a for a in args if a != str(maxf)]
    os.makedirs(OUT, exist_ok=True)
    paths = set()
    for d in (args or DIRS):
        for ext in ("ttf", "otf"):
            paths |= set(glob.glob(os.path.join(d, "**", "*." + ext), recursive=True))

    rng = random.Random(20260920)
    fonts = pairs_n = same = mism = hits = 0
    fmt1 = fmt2 = ext = 0
    for p in sorted(paths):
        if fonts >= maxf:
            break
        try:
            f = TTFont(p, fontNumber=0, lazy=False)
            if "GPOS" not in f:
                continue
            lookups = kern_lookups(f["GPOS"].table)
            if not lookups:
                continue
            order = f.getGlyphOrder()
            gid = {n: i for i, n in enumerate(order)}
            covered = []
            for lk in lookups:
                for st in subtables(lk):
                    if st is None:
                        continue
                    if st.Format == 1:
                        fmt1 += 1
                    else:
                        fmt2 += 1
                    if lk.LookupType == 9:
                        ext += 1
                    covered += list(st.Coverage.glyphs)
            if not covered:
                continue
            uniq = sorted(set(covered), key=lambda n: gid.get(n, 1 << 30))
            uniq = [n for n in uniq if n in gid]
            sample = uniq[:SAMPLE - 15] if len(uniq) > SAMPLE - 15 else list(uniq)
            # ...plus glyphs that are NOT in any coverage, so misses are exercised too
            outside = [n for n in order if n not in set(covered)]
            sample += rng.sample(outside, min(15, len(outside)))
        except Exception:
            continue

        want, keys = [], []
        for a in sample:
            for b in sample:
                keys.append((gid[a], gid[b]))
                want.append(reference(lookups, a, b))
        f.close()
        got = rekha_values(p, keys)
        if got is None:
            continue
        fonts += 1
        bad = 0
        for i in range(len(keys)):
            pairs_n += 1
            if want[i]:
                hits += 1
            if got[i] == want[i]:
                same += 1
            else:
                mism += 1
                bad += 1
                if bad <= 2:
                    print("  MISMATCH %s gids %s: fontTools %d rekha %d"
                          % (os.path.basename(p), keys[i], want[i], got[i]))
        print("  %-46s %6d pairs%s" % (os.path.basename(p), len(keys),
                                       "" if bad == 0 else "   <-- MISMATCHES"))

    print("\n%d fonts, %d pairs: %d identical, %d mismatched" % (fonts, pairs_n, same, mism))
    print("%d of those pairs carry a non-zero kern; the rest prove the misses" % hits)
    print("subtables seen: %d PairPos format 1, %d format 2, %d behind an extension lookup"
          % (fmt1, fmt2, ext))
    return 0 if (mism == 0 and pairs_n) else 1


if __name__ == "__main__":
    sys.exit(main(sys.argv))
