#!/usr/bin/env python3
"""FreeType's own hinted outlines of the embedded face, as the oracle for rekha's glyph zone (0.8.2).

⛔ THIS SCRIPT IS THE ONE PIECE OF EVIDENCE rekha CANNOT PRODUCE FOR ITSELF on a real font.
programs/hint_unit_vectors.cyr (scripts/hint_unit_vectors.py) pins every point instruction on a
synthetic glyph; this one runs Liberation Sans's actual glyph programs — fpgm, prep and all —
through the interpreter the world's hinted fonts were drawn against, and records the result
point for point. Its consumer is programs/hint_test.cyr's group P (0.8.2, the release that loads
a glyph into zone 1 and answers a hinted outline), which reads the emitted module
programs/hint_glyph_vectors.cyr the way group K reads hint_unit_vectors.cyr.

FreeType is reached through scripts/ftshim.py: the CLASSIC interpreter (`GETINFO` 35), which is
what src/hint.cyr implements — the default since FreeType 2.7 is version 40, whose minimal
subpixel hinting suppresses every horizontal move (at 12 ppem it leaves the 'H' stem at x=420
where v35 puts it at 439) — and FT_LOAD_NO_AUTOHINT. The reference is FreeType 2.14.3; ftshim
refuses any other 2.x minor, because CI's Ubuntu ships 2.13.2 and its move arithmetic differs.

Every face is WARMED once at a throwaway ppem before anything is measured: FreeType runs `fpgm`
at the first size a face is hinted at, with that size's metrics (2.14.3, C2 B5), so a table whose
first row ran fpgm at 8 ppem would differ from one that started at 48 wherever fpgm asked MPPEM.
rekha does the same (D11: fpgm once, at the first size asked for); the consumer builds its first
context at WARM_PPEM before it compares anything.

THE ROWS. The 18 characters of CHARS (all simple glyphs with a program) at the 10 ppems of PPEMS,
plus the SPECIAL glyphs — composites (accented letters with USE_MY_METRICS on component 0 and a
composite program, one program-less composite, the one composite whose program contains IUP, a
composite of an empty glyph, two whose scaled offsets land on an exact negative half pixel where
FreeType's floor rounding and half-away rounding disagree), the space (an empty glyph: four
phantoms, no outline) and a program-less simple glyph. Every special is picked BY GID with its
reason stated in SPECIALS; the emitter cross-checks the gid against the cmap where the glyph has
a code point, and against the raw glyf record for the structural claims (composite or not,
program or not, USE_MY_METRICS), so a different face fails loudly instead of emitting a table
that pins the wrong glyph. Size budget: simple rows (and the empty glyph) at all 10 ppems,
composite rows at COMPOSITE_PPEMS only — 12, 16 and 24, which are where é's, Ä's, ½'s and ľ's
composite programs are seen to act and where ͼ (12) and ͣ (24) hit their negative halves — so
the module stays near 4,500 lines instead of 5,600; the header of the module says so.

EVERY ROW IS ALSO LOADED UNDER FT_LOAD_PEDANTIC on a second face (warmed pedantic too) and must
give the same points, tags and advance: the proof that FreeType skipped nothing silently on any
row (a bad point index, a short stack, a cvt index out of range fail the load in pedantic mode
and pass with the instruction dropped otherwise).

WHAT A ROW RECORDS is exactly what FreeType's glyph slot holds after FT_Load_Glyph, nothing
derived: every outline point's x and y in F26Dot6 AS REPORTED — after TT_Load_Glyph translated
the outline by -pp1.x (ref2143/ttgload.c:2578-2583; on this face lsb == xMin for every glyph, so
pp1.x is 0 and the translation subtracts 0), the raw tag byte (on-curve 1, touch-x 8, touch-y 16,
and on the first point of every glyph or component whose program ran, 4 | scan_type << 5), the
contour ends, and slot->advance.x (the base layer's FT_PIX_ROUND_LONG of pp2.x - pp1.x). The
unhinted scaled outline is NOT recorded: rekha computes it.

THE EMITTER CHECKS ITS OWN OUTPUT before writing it (the gates of scripts/hint_unit_vectors.py,
imported from there): no line over 120 bytes, none of cyrlint's deferral words, `cyrius lint
--strict` with zero warn/deferral lines, `cyrius fmt` on a copy that must come back
byte-identical. Any failure leaves the destination untouched. The output is deterministic: two
emits on the same host and FreeType are byte-identical.

No freetype-py, no fontTools. NOT RUN IN CI: CI's Ubuntu ships FreeType 2.13.2, whose move
arithmetic, ODD/EVEN, stack margin and DELTAP pops differ from the 2.14.3 rekha targets; the
committed module is regenerated by hand on a 2.14.x host and reviewed like any other
transcription. Python 3 stdlib only. Modes:

    python3 scripts/hint_glyph_vectors.py emit programs/hint_glyph_vectors.cyr
    python3 scripts/hint_glyph_vectors.py table            # the 18 x 10 digest table (0.8.1's)
    python3 scripts/hint_glyph_vectors.py dump H 12        # every point of one glyph (char or gid)
    python3 scripts/hint_glyph_vectors.py sweep            # how much of the face hinting moves
    python3 scripts/hint_glyph_vectors.py rows             # the row list with reasons and counts
"""
import os
import shutil
import struct
import sys
import tempfile

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import ftshim  # noqa: E402
import hint_unit_vectors as hu  # noqa: E402  (its emitter gates and helpers)

FACE = "fonts/LiberationSans-Regular.ttf"
FNV_OFFSET = 0xCBF29CE484222325
FNV_PRIME = 0x100000001B3
M64 = 0xFFFFFFFFFFFFFFFF

# The characters the suite pins, chosen for what they exercise rather than for coverage:
# stems and a crossbar (H), a single stem (I l), curves (o e O), a diagonal (A W), a dot (i .),
# a descender (g j p), many points (m), and a digit with two counters (8).
CHARS = "HIloenAB08.,mWgjpi"
PPEMS = (8, 9, 11, 12, 13, 16, 18, 24, 32, 48)
COMPOSITE_PPEMS = (12, 16, 24)  # the composite rows' ppems (see the docstring: the size budget)
WARM_PPEM = 64  # not in PPEMS: where fpgm runs, and where the consumer must start too
SWEEP_PPEM = 12

# Composite record flags (ref2143/ttgload.c TT_Load_Composite_Glyph / tttypes.h).
ARGS_ARE_WORDS = 0x0001
ARGS_ARE_XY_VALUES = 0x0002
ROUND_XY_TO_GRID = 0x0004
WE_HAVE_A_SCALE = 0x0008
MORE_COMPONENTS = 0x0020
WE_HAVE_AN_XY_SCALE = 0x0040
WE_HAVE_A_2X2 = 0x0080
WE_HAVE_INSTR = 0x0100
USE_MY_METRICS = 0x0200
SCALED_COMPONENT_OFFSET = 0x0800
UNSCALED_COMPONENT_OFFSET = 0x1000

# The special rows: (gid, code point or None, kind, why). `kind` is what the raw glyf record must
# say — "composite", "composite-noprog", "empty", "simple-noprog" — and `umm` whether component 0
# carries USE_MY_METRICS; both are asserted against the file before any row is measured.
SPECIALS = [
    (171, 0xE9, "composite", True,
     "e + acute: 2 components, USE_MY_METRICS on component 0, a 20-byte composite program (CALL "
     "SRP1 SHC[1] ...) that moves points at 12 ppem"),
    (135, 0xC5, "composite", True,
     "A + ring: USE_MY_METRICS on component 0 inherits A's program-moved pp2 (advance 448, not 512, "
     "at 12 ppem); a 43-byte program with DELTAP1 x4 and MIAP[1] that acts at every ppem"),
    (134, 0xC4, "composite", True,
     "A + diaeresis: inherits A's moved pp2; its program acts at 12 and 16 ppem"),
    (142, 0xCC, "composite", True,
     "I + grave: USE_MY_METRICS on component 0, a NEGATIVE offset (-97) in BYTE arguments (flags "
     "0x1106) on component 1; program acts at 16 ppem"),
    (127, 0xBD, "composite", False,
     "one half: 3 components, no USE_MY_METRICS, its own program moves pp2 and is THE composite "
     "program of this face that runs IUP[x] IUP[y]"),
    (126, 0xBC, "composite-noprog", False,
     "one quarter: 3 components, NO composite program (the assembly of hinted components IS the "
     "answer; component touch bits survive), negative offsets, a program-less component (gid 2054)"),
    (210, 0x110, "composite-noprog", True,
     "D with stroke: 1 component, USE_MY_METRICS, no program: phantoms carried, never rounded by a "
     "composite run, the advance grid-fit by the base layer alone"),
    (98, 0xA0, "composite-noprog", False,
     "no-break space: a composite of the EMPTY glyph 3 at offset (0, 0): zero points, the advance "
     "from its own hmtx"),
    (256, 0x13E, "composite", False,
     "l + caron: no USE_MY_METRICS, its own program moves pp2 (advance differs from grid(own aw) "
     "at 16 and 24 ppem)"),
    (822, 0x37C, "composite", True,
     "Greek small dotted lunate sigma: component offset dy -769 scales to -288 at 12 ppem, an "
     "exact negative half: FT_PIX_ROUND (floor form) gives -256 where half-away gives -320"),
    (805, 0x363, "composite-noprog", False,
     "combining Latin small a: no program, one component at dx -384, which is -288 at 24 ppem (floor "
     "-256, half-away -320) and -144 / -192 at 12 / 16"),
    (100, 0xA2, "simple-noprog", None,
     "cent: a SIMPLE glyph with n_ins 0: scaled unrounded points, rounded phantoms, no touch bits, "
     "no scan bits on point 0, the advance grid-fit"),
    (3, 0x20, "empty", None,
     "space: the empty glyph (loca[3] == loca[4]): four phantoms only, 0 points, 0 contours, "
     "advance grid(MulFix(569, scale))"),
]


def fnv_u32(h, v):
    """The 32-bit-wide feed programs/face_test.cyr uses, in 64-bit FNV-1a."""
    v &= M64
    for i in range(4):
        h = ((h ^ ((v >> (i * 8)) & 255)) * FNV_PRIME) & M64
    return h


def digest(points):
    h = FNV_OFFSET
    for x, y in points:
        h = fnv_u32(h, x)
        h = fnv_u32(h, y)
    return h


def open_face(pedantic=False):
    """The embedded face, warmed: its fpgm has run at WARM_PPEM before any row is measured (the
    pedantic twin is warmed pedantic, so fpgm and prep are checked too)."""
    face = ftshim.load_face(FACE)
    ftshim.hinted(face, WARM_PPEM, ftshim.char_index(face, "H"), pedantic=pedantic)
    return face


# ----------------------------------------------------------------------------------------------
# The raw glyf record: what the file says a glyph is, independent of FreeType.
# ----------------------------------------------------------------------------------------------
class Glyf(object):
    """Table directory, loca and glyf of an sfnt, enough to classify a glyph and list its
    component records (the same walk ref2143/ttgload.c:549-736 does)."""

    def __init__(self, data):
        self.data = data
        n = struct.unpack(">H", data[4:6])[0]
        self.tables = {}
        for i in range(n):
            tag, _, off, ln = struct.unpack(">4sIII", data[12 + 16 * i : 28 + 16 * i])
            self.tables[tag] = data[off : off + ln]
        head = self.tables[b"head"]
        self.upem = struct.unpack(">H", head[18:20])[0]
        self.long_loca = struct.unpack(">h", head[50:52])[0] != 0
        self.num_glyphs = struct.unpack(">H", self.tables[b"maxp"][4:6])[0]
        self.loca = self.tables[b"loca"]
        self.glyf = self.tables[b"glyf"]

    def loc(self, g):
        if self.long_loca:
            return struct.unpack(">I", self.loca[4 * g : 4 * g + 4])[0]
        return struct.unpack(">H", self.loca[2 * g : 2 * g + 2])[0] * 2

    def record(self, g):
        a, b = self.loc(g), self.loc(g + 1)
        return self.glyf[a:b] if b > a else b""

    def kind(self, g):
        """'empty', 'simple' or 'composite' from the record's own header."""
        d = self.record(g)
        if len(d) < 10:
            return "empty"
        nc = struct.unpack(">h", d[:2])[0]
        return "composite" if nc < 0 else ("empty" if nc == 0 else "simple")

    def simple_n_ins(self, g):
        d = self.record(g)
        nc = struct.unpack(">h", d[:2])[0]
        p = 10 + 2 * nc
        return struct.unpack(">H", d[p : p + 2])[0]

    def simple_program(self, g):
        d = self.record(g)
        nc = struct.unpack(">h", d[:2])[0]
        p = 10 + 2 * nc
        n = struct.unpack(">H", d[p : p + 2])[0]
        return d[p + 2 : p + 2 + n]

    def components(self, g):
        """[(flags, gid, arg1, arg2, (xx, xy, yx, yy) or None)], n_ins of the composite program
        (0 when the last record lacks WE_HAVE_INSTR), and the program bytes."""
        d = self.record(g)
        p, out = 10, []
        while True:
            flags, gid = struct.unpack(">HH", d[p : p + 4])
            p += 4
            if flags & ARGS_ARE_WORDS:
                fmt = ">hh" if flags & ARGS_ARE_XY_VALUES else ">HH"
                a1, a2 = struct.unpack(fmt, d[p : p + 4])
                p += 4
            else:
                fmt = ">bb" if flags & ARGS_ARE_XY_VALUES else ">BB"
                a1, a2 = struct.unpack(fmt, d[p : p + 2])
                p += 2
            m = None
            if flags & WE_HAVE_A_SCALE:
                s = struct.unpack(">h", d[p : p + 2])[0]
                m = (s, 0, 0, s)
                p += 2
            elif flags & WE_HAVE_AN_XY_SCALE:
                sx, sy = struct.unpack(">hh", d[p : p + 4])
                m = (sx, 0, 0, sy)
                p += 4
            elif flags & WE_HAVE_A_2X2:
                m = struct.unpack(">hhhh", d[p : p + 8])
                p += 8
            out.append((flags, gid, a1, a2, m))
            if not flags & MORE_COMPONENTS:
                break
        n_ins, prog = 0, b""
        if flags & WE_HAVE_INSTR:
            n_ins = struct.unpack(">H", d[p : p + 2])[0]
            prog = d[p + 2 : p + 2 + n_ins]
        return out, n_ins, prog


def flag_names(flags):
    names = []
    for bit, nm in (
        (ARGS_ARE_WORDS, "WORDS"), (ARGS_ARE_XY_VALUES, "XY"), (ROUND_XY_TO_GRID, "ROUND_XY"),
        (WE_HAVE_A_SCALE, "SCALE"), (WE_HAVE_AN_XY_SCALE, "XY_SCALE"), (WE_HAVE_A_2X2, "2X2"),
        (WE_HAVE_INSTR, "INSTR"), (USE_MY_METRICS, "USE_MY_METRICS"),
        (SCALED_COMPONENT_OFFSET, "SCALED_OFFSET"), (UNSCALED_COMPONENT_OFFSET, "UNSCALED_OFFSET"),
    ):
        if flags & bit:
            names.append(nm)
    return " ".join(names)


# ----------------------------------------------------------------------------------------------
# The rows
# ----------------------------------------------------------------------------------------------
def char_label(cp):
    """'H' for a printable ASCII code point, else U+XXXX — the row name and the header's label."""
    if cp is not None and 0x21 <= cp <= 0x7E:
        return chr(cp)
    return "U+%04X" % cp if cp is not None else "gid"


def glyph_list(face, gf):
    """[(gid, cp, kind, why, ppems)] — the 18 characters then the specials, each cross-checked
    against the cmap and the raw glyf record."""
    out = []
    for ch in CHARS:
        gid = ftshim.char_index(face, ch)
        assert gf.kind(gid) == "simple" and gf.simple_n_ins(gid) > 0, (ch, gid)
        out.append((gid, ord(ch), "simple", "a simple glyph with a program (0.8.1's oracle)", PPEMS))
    for gid, cp, kind, umm, why in SPECIALS:
        assert gid < gf.num_glyphs, gid
        if cp is not None:
            assert ftshim.char_index(face, cp) == gid, "gid %d is not U+%04X on this face" % (gid, cp)
        raw = gf.kind(gid)
        if kind == "empty":
            assert raw == "empty", (gid, raw)
            ppems = PPEMS
        elif kind == "simple-noprog":
            assert raw == "simple" and gf.simple_n_ins(gid) == 0, (gid, raw)
            ppems = PPEMS
        else:
            assert raw == "composite", (gid, raw)
            comps, n_ins, _ = gf.components(gid)
            assert (n_ins > 0) == (kind == "composite"), (gid, kind, n_ins)
            assert bool(comps[0][0] & USE_MY_METRICS) == umm, (gid, hex(comps[0][0]))
            ppems = COMPOSITE_PPEMS
        out.append((gid, cp, kind, why, ppems))
    return out


def measure_row(face, strict, gid, ppem):
    """One row: FreeType's reported points, tags, contour ends and advance, and the same load
    under FT_LOAD_PEDANTIC on the second face, which must agree."""
    points, tags, ends, adv = ftshim.load_glyph(face, ppem, gid, 0)
    p2, t2, e2, a2 = ftshim.load_glyph(strict, ppem, gid, ftshim.FT_LOAD_PEDANTIC)
    assert (p2, t2, e2, a2) == (points, tags, ends, adv), "gid %d at %d: pedantic differs" % (gid, ppem)
    return {"gid": gid, "ppem": ppem, "points": points, "tags": tags, "ends": ends, "advance": adv}


def measure_all():
    face, strict = open_face(), open_face(pedantic=True)
    gf = Glyf(open(FACE, "rb").read())
    glyphs = glyph_list(face, gf)
    rows = []
    for k, (gid, cp, kind, why, ppems) in enumerate(glyphs):
        first = None
        for ppem in ppems:
            r = measure_row(face, strict, gid, ppem)
            r["glyph"], r["cp"], r["kind"] = k, cp, kind
            if first is None:
                first = r
            # the structure is the glyph's, not the size's: one table of ends per glyph
            assert (len(r["points"]), r["ends"]) == (len(first["points"]), first["ends"]), (gid, ppem)
            rows.append(r)
    ftshim.done(face)
    ftshim.done(strict)
    return glyphs, rows, gf


# ----------------------------------------------------------------------------------------------
# The Cyrius module
# ----------------------------------------------------------------------------------------------
def row_name(r):
    return "%s %d" % (char_label(r["cp"]), r["ppem"])


def glyph_desc(gf, gid, kind):
    """One line of structure for the header: contours/points, n_ins, and the component records."""
    if kind == "empty":
        return "empty glyph, 0 points"
    if kind.startswith("simple"):
        return "simple, %d-byte program" % gf.simple_n_ins(gid)
    comps, n_ins, _ = gf.components(gid)
    parts = ["[0x%04x gid %d (%d, %d)]" % (fl, g, a1, a2) for fl, g, a1, a2, _ in comps]
    return "composite, %d-byte program, components %s" % (n_ins, " ".join(parts))


def module_lines(glyphs, rows, gf):
    ver = ftshim.version_string()
    n = len(rows)
    n_simple_rows = sum(1 for r in rows if r["kind"] in ("simple", "simple-noprog", "empty"))
    n_pts = sum(len(r["points"]) for r in rows)
    L = []
    L += [
        "# programs/hint_glyph_vectors.cyr — GENERATED by scripts/hint_glyph_vectors.py from FreeType %s" % ver,
        "# (classic interpreter, GETINFO version 35, grayscale, FT_LOAD_NO_AUTOHINT). DO NOT EDIT.",
        "#",
        "# FreeType's own HINTED OUTLINES of the embedded face (%s, fonts/face_data.cyr):" % FACE,
        "# %d rows over %d glyphs, %d points in all. Each row is one (glyph, ppem): every outline" % (n, len(glyphs), n_pts),
        "# point's position as FreeType's glyph slot REPORTS it (F26Dot6), its raw tag byte, the contour",
        "# ends, and slot->advance.x. The face was warmed at %d ppem first (fpgm runs at the first size a" % WARM_PPEM,
        "# face is hinted at; the consumer must start there too). Every row was ALSO loaded under",
        "# FT_LOAD_PEDANTIC on a second warmed face and gave the same points, tags and advance, so no",
        "# instruction was skipped silently on any row. Nothing here was computed by rekha.",
        "#",
        "# ⛔ NOT REGENERATED IN CI. CI's Ubuntu ships FreeType 2.13.2, whose move arithmetic, ODD/EVEN",
        "# test, stack margin and DELTAP pop discipline differ from the 2.14.3 rekha targets. Regenerate",
        "# by hand on a 2.14.x host with",
        "#   python3 scripts/hint_glyph_vectors.py emit programs/hint_glyph_vectors.cyr",
        "# and review the diff like any other transcription. The emitter lints and formats its output",
        "# before writing it, so this file is gate-clean by construction, and two emits are identical.",
        "#",
        "# The contract (each rule measured on FreeType, ref2143/ = FreeType 2.14.3's sources):",
        "#   * hg_want_x(r, i) is the REPORTED x of outline point i: the interpreter's cur.x MINUS",
        "#     cur[pp1].x, because TT_Load_Glyph translates the hinted outline so that pp1 is the origin",
        "#     (ttgload.c:2578-2583). On this face lsb == xMin for every glyph and no program moves pp1,",
        "#     so the subtraction is of 0 — compare cur.x - cur[pp1].x anyway; that is the contract.",
        "#     hg_want_y(r, i) is cur.y as it is. Phantom points are never in the outline.",
        "#   * hg_want_tag(r, i) is the raw tag byte: 1 on-curve, 8 touched in x, 16 touched in y; and",
        "#     4 (FT_CURVE_TAG_HAS_SCANMODE) with scan_type << 5 in bits 5-7 on the FIRST point of every",
        "#     simple glyph whose program ran (ttgload.c:839-840) and, inside a composite, on the first",
        "#     point of every component whose program ran (the composite program's own write lands on",
        "#     a phantom slot and is invisible). Mask with 0x19 (25) for the interpreter's bits — bit 2",
        "#     and bits 5-7 are scan bits rekha does not keep: 1 -> ONCURVE, 8 -> TOUCHX, 16 -> TOUCHY.",
        "#     A composite WITH a program has every component's touch bits cleared before its program",
        "#     runs (ttgload.c:1245-1246); a composite WITHOUT one keeps them; a program-less simple",
        "#     glyph has none and no scan bits.",
        "#   * hg_want_advance(r) is slot->advance.x: pp2.x - pp1.x after the base layer's grid fit",
        "#     (ftobjs.c:897), i.e. ((cur[pp2].x - cur[pp1].x) + 32) & -64 — FT_PIX_ROUND's floor form.",
        "#     For a USE_MY_METRICS composite the phantoms are the component's (program-moved pp2 and",
        "#     all); for an empty glyph and a program-less composite they were never rounded and only",
        "#     this rounding makes the advance whole.",
        "#   * hg_row_contours(r) / hg_row_end(r, c) are the outline's contour count and end indices",
        "#     (absolute, phantoms excluded), the same at every ppem of a glyph.",
        "#   * the ppems: simple rows and the empty glyph at %s;" % ", ".join(str(p) for p in PPEMS),
        "#     composite rows at %s only (size budget: ~5,600 lines at all ten, LINECOUNT" % ", ".join(str(p) for p in COMPOSITE_PPEMS),
        "#     this way), chosen where their programs are seen to act and where the two negative-half",
        "#     offsets fall. scripts/hint_glyph_diff.py sweeps every glyph at every ppem on a dev host.",
        "#",
        "# Accessors (all null-safe: anything out of range answers 0):",
        "#   hg_ft_version()                  cstring, the FreeType that produced this file",
        "#   hg_row_count()                   %d rows, r in 0..%d, glyph-major then ppem-ascending" % (n, n - 1),
        "#   hg_row_name(r)                   cstring, the char (or U+ hex) and the ppem, for check_named",
        "#   hg_row_gid(r) / hg_row_ppem(r)   the glyph and the size",
        "#   hg_row_points(r) / hg_row_contours(r) / hg_row_end(r, c)   n points (no phantoms), n contours, ends",
        "#   hg_want_x/y/tag(r, i)            reported x, y and raw tag of point i < hg_row_points(r)",
        "#   hg_want_advance(r)               slot->advance.x",
        "#",
        "# The glyphs, in row order (rows %d..%d are the %d simple/empty rows at ten ppems each):" % (0, n_simple_rows - 1, n_simple_rows // len(PPEMS)),
    ]
    for k, (gid, cp, kind, why, ppems) in enumerate(glyphs):
        L += hu._wrap("#   %d: %s gid %d —" % (k, char_label(cp), gid), "%s: %s" % (glyph_desc(gf, gid, kind), why))
    L += [
        "",
        'fn hg_ft_version(): i64 { return "%s"; }' % ver,
        "",
        "fn hg_row_count(): i64 { return %d; }" % n,
        "",
        "fn hg_pick(f, x, y, t): i64 {",
        "    if (f == 0) { return x; }",
        "    if (f == 1) { return y; }",
        "    return t;",
        "}",
        "",
        "# Per glyph: gid, point count, contour count, contour ends.",
        "fn hg_glyph_gid(k): i64 {",
    ]
    hu._pairs(L, ["if (k == %d) { return %d; }" % (k, g[0]) for k, g in enumerate(glyphs)], 3)
    L += ["    return 0;", "}", ""]
    firsts = {}
    for r in rows:
        firsts.setdefault(r["glyph"], r)
    L.append("fn hg_glyph_points(k): i64 {")
    hu._pairs(L, ["if (k == %d) { return %d; }" % (k, len(firsts[k]["points"])) for k in range(len(glyphs))], 3)
    L += ["    return 0;", "}", ""]
    L.append("fn hg_glyph_contours(k): i64 {")
    hu._pairs(L, ["if (k == %d) { return %d; }" % (k, len(firsts[k]["ends"])) for k in range(len(glyphs))], 3)
    L += ["    return 0;", "}", ""]
    L.append("fn hg_glyph_end(k, c): i64 {")
    items = []
    for k in range(len(glyphs)):
        for c, e in enumerate(firsts[k]["ends"]):
            items.append("if (k == %d) { if (c == %d) { return %d; } }" % (k, c, e))
    hu._pairs(L, items, 2)
    L += ["    return 0;", "}", ""]
    L.append("# Per row: the glyph index (-1 for a row out of range, so the per-glyph readers answer 0),")
    L.append("# the ppem, the name, the advance.")
    L.append("fn hg_row_glyph(r): i64 {")
    hu._pairs(L, ["if (r == %d) { return %d; }" % (i, r["glyph"]) for i, r in enumerate(rows)], 3)
    L += ["    return 0 - 1;", "}", ""]
    L.append("fn hg_row_ppem(r): i64 {")
    hu._pairs(L, ["if (r == %d) { return %d; }" % (i, r["ppem"]) for i, r in enumerate(rows)], 3)
    L += ["    return 0;", "}", ""]
    L.append("fn hg_row_name(r): i64 {")
    hu._pairs(L, ['if (r == %d) { return "%s"; }' % (i, row_name(r)) for i, r in enumerate(rows)], 3)
    L += ["    return 0;", "}", ""]
    L.append("fn hg_want_advance(r): i64 {")
    hu._pairs(L, ["if (r == %d) { return %d; }" % (i, r["advance"]) for i, r in enumerate(rows)], 3)
    L += [
        "    return 0;",
        "}",
        "",
        "fn hg_row_gid(r): i64 { return hg_glyph_gid(hg_row_glyph(r)); }",
        "fn hg_row_points(r): i64 { return hg_glyph_points(hg_row_glyph(r)); }",
        "fn hg_row_contours(r): i64 { return hg_glyph_contours(hg_row_glyph(r)); }",
        "fn hg_row_end(r, c): i64 { return hg_glyph_end(hg_row_glyph(r), c); }",
        "",
        "# The rows. hg_e<r>(i, f) is the expected x (f 0), y (f 1) and tag (f 2) of outline point i;",
        "# the comment above each names the row and its digest as `hint_glyph_vectors.py table` prints it.",
    ]
    for i, r in enumerate(rows):
        L.append("# %d %s — gid %d, %d ppem, %d points, advance %d, digest 0x%016x" % (
            i, row_name(r), r["gid"], r["ppem"], len(r["points"]), r["advance"], digest(r["points"])))
        L.append("fn hg_e%d(i, f): i64 {" % i)
        hu._pairs(
            L,
            ["if (i == %d) { return hg_pick(f, %d, %d, %d); }" % (j, x, y, r["tags"][j])
             for j, (x, y) in enumerate(r["points"])],
            2,
        )
        L += ["    return 0;", "}", ""]
    L += [
        "fn hg_want(r, i, f): i64 {",
        "    if (i < 0) { return 0; }",
        "    if (i >= hg_row_points(r)) { return 0; }",
    ]
    hu._pairs(L, ["if (r == %d) { return hg_e%d(i, f); }" % (i, i) for i in range(n)], 3)
    L += [
        "    return 0;",
        "}",
        "",
        "fn hg_want_x(r, i): i64 { return hg_want(r, i, 0); }",
        "fn hg_want_y(r, i): i64 { return hg_want(r, i, 1); }",
        "fn hg_want_tag(r, i): i64 { return hg_want(r, i, 2); }",
        "",
    ]
    # the header quotes the file's own line count; the substitution changes no line count
    L = [ln.replace("LINECOUNT", "%d" % len(L)) for ln in L]
    return L


def emit(path):
    glyphs, rows, gf = measure_all()
    L = module_lines(glyphs, rows, gf)
    hu.self_check(L)
    src = "\n".join(L)
    tmpdir = tempfile.mkdtemp(prefix="hint_glyph_vectors.")
    try:
        cand = os.path.join(tmpdir, os.path.basename(path))
        open(cand, "w").write(src)
        why = hu._lint_ok(cand) or hu._fmt_ok(cand, tmpdir)
        if why:
            sys.exit("refusing to write %s:\n%s" % (path, why))
        shutil.move(cand, path)
    finally:
        shutil.rmtree(tmpdir, ignore_errors=True)
    print("wrote %s: FreeType %s, %d glyphs, %d rows, %d points, %d lines, lint --strict and fmt clean"
          % (path, ftshim.version_string(), len(glyphs), len(rows), sum(len(r["points"]) for r in rows), len(L)))


# ----------------------------------------------------------------------------------------------
# The other modes
# ----------------------------------------------------------------------------------------------
def resolve(face, tok):
    """A gid from a decimal token, else the cmap index of the character."""
    if tok.isdigit():
        return int(tok), "gid %s" % tok
    return ftshim.char_index(face, tok), repr(tok)


def cmd_rows(argv):
    glyphs, rows, gf = measure_all()
    print("# FreeType %s, %s: %d glyphs, %d rows, %d points" % (
        ftshim.version_string(), FACE, len(glyphs), len(rows), sum(len(r["points"]) for r in rows)))
    for k, (gid, cp, kind, why, ppems) in enumerate(glyphs):
        n = len([r for r in rows if r["glyph"] == k])
        print("%2d %-7s gid %4d %-16s %2d rows  %s" % (k, char_label(cp), gid, kind, n, why))
        print("        " + glyph_desc(gf, gid, kind))


def cmd_dump(argv):
    tok = argv[0] if argv else "H"
    ppem = int(argv[1]) if len(argv) > 1 else 12
    face = open_face()
    gid, label = resolve(face, tok)
    pts, tags, cts, adv = ftshim.load_glyph(face, ppem, gid, 0)
    raw, _, radv = ftshim.hinted(face, ppem, gid, hint=False)
    comp = " composite" if ftshim.is_composite(face, gid) else ""
    print(f"{label} gid={gid}{comp} ppem={ppem} contours={cts} advance {radv} -> {adv} (26.6)")
    print(f"{'i':>4} {'on':>3} {'unhinted':>16} {'hinted':>16}   delta  tag")
    for i, (p, q) in enumerate(zip(raw, pts)):
        on = tags[i] & 1
        d = (q[0] - p[0], q[1] - p[1])
        mark = "   " if d == (0, 0) else " * "
        print(f"{i:>4} {on:>3} {str(p):>16} {str(q):>16}{mark}{str(d) if d != (0, 0) else '':<10} {tags[i]}")
    print(f"digest 0x{digest(pts):016x}")


def cmd_table(argv):
    face = open_face()
    print(f"# FreeType {ftshim.version_string()} interpreter-version {ftshim.INTERPRETER_VERSION}, {FACE}, "
          f"fpgm warmed at {WARM_PPEM} ppem")
    print(f"# {'ch':>3} {'gid':>5} {'ppem':>5} {'pts':>5} {'adv':>6}  digest")
    for ch in CHARS:
        gid = ftshim.char_index(face, ch)
        comp = "composite" if ftshim.is_composite(face, gid) else ""
        for ppem in PPEMS:
            pts, tags, adv = ftshim.hinted(face, ppem, gid)
            print(f"  {ch!r:>3} {gid:>5} {ppem:>5} {len(pts):>5} {adv:>6}  0x{digest(pts):016x} {comp}")


def cmd_sweep(argv):
    """How much of the face the oracle covers, split the way rekha will have to."""
    import collections

    face = open_face()
    n = face.num_glyphs
    kinds = collections.Counter()
    moved = 0
    for gid in range(n):
        try:
            pts, _, _ = ftshim.hinted(face, SWEEP_PPEM, gid)
            raw, _, _ = ftshim.hinted(face, SWEEP_PPEM, gid, hint=False)
        except ftshim.FTError:
            kinds["error"] += 1
            continue
        kinds["composite" if ftshim.is_composite(face, gid) else "simple"] += 1
        if pts != raw:
            moved += 1
    print(f"{FACE}: {dict(kinds)}, {moved} of {n} glyphs move under hinting at {SWEEP_PPEM} ppem")


def main():
    cmds = {"emit": None, "dump": cmd_dump, "table": cmd_table, "sweep": cmd_sweep, "rows": cmd_rows}
    if len(sys.argv) < 2 or sys.argv[1] not in cmds:
        print(__doc__)
        return 2
    if sys.argv[1] == "emit":
        emit(sys.argv[2] if len(sys.argv) > 2 else "programs/hint_glyph_vectors.cyr")
        return 0
    return cmds[sys.argv[1]](sys.argv[2:]) or 0


if __name__ == "__main__":
    sys.exit(main())
