#!/usr/bin/env python3
"""kern_diff.py — every kerning pair of every `kern` font on this machine, against fontTools.

    python3 scripts/kern_diff.py [font-dir ...]      # needs fontTools; non-zero on any mismatch

For each font it finds with a `kern` table, it asks fontTools for the pairs, asks rekha for the
same pairs, and compares. It also asks rekha for a sample of pairs fontTools says are NOT there,
because a lookup that returns the neighbouring entry passes an every-pair check perfectly.

⚠ WHAT THE REFERENCE IS, PRECISELY. fontTools PARSES the table — subtable walk, endianness, the
pair array — and that is the half this settles. It does not decide what to DO with several
subtables, so the accumulate / override / skip rule is rekha's in both columns and is modelled
here. The script reports how many fonts have a single applicable subtable, where that question does
not arise and the comparison is parse against parse with nothing in between.

⛔ THIS IS A DEV-HOST DIFFERENTIAL, not a committed one: it reads the machine's installed fonts,
which are not in this repo and are not the same on another machine. `scripts/cff2_wide_diff.py`,
`scripts/cff_fontmatrix_diff.py` and `scripts/metrics_var_diff.py` build their own input and are
reproducible anywhere; this one is in the same class as rekha's CFF and WOFF2 corpus sweeps. Run it
and record the counts.

⛔ Compiles and runs a throwaway Cyrius program under build/ (gitignored). Run from the repo root.
"""
import glob
import os
import struct
import subprocess
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO, "build")
DIRS = ["/usr/share/fonts", os.path.expanduser("~/.local/share/fonts"),
        os.path.expanduser("~/.fonts")]
ABSENT_SAMPLE = 500

DUMPER = r'''# GENERATED by scripts/kern_diff.py — throwaway, under build/.
include "programs/prelude.cyr"

fn main(): i64 {
    alloc_init();
    var cap = 33554432;
    var buf = alloc(cap);
    var n = file_read_all("__FONT__", buf, cap);
    if (n <= 0) { syscall(1, 2, "read failed\n", 12); return 1; }
    var f = rekha_font_open(buf, n);
    if (f == 0) { syscall(1, 1, "NOFONT\n", 7); return 0; }
    var pcap = 16777216;
    var pb = alloc(pcap);
    var pn = file_read_all("__PAIRS__", pb, pcap);
    if (pn < 4) { syscall(1, 2, "pairs failed\n", 13); return 1; }
    var np = load64(pb);
    var i = 0;
    while (i < np) {
        fmt_int(rekha_kern_pair(f, load64(pb + 8 + i * 16), load64(pb + 16 + i * 16)));
        syscall(1, 1, "\n", 1);
        i = i + 1;
    }
    return 0;
}

var exit_code = main();
syscall(60, exit_code);
'''


def applicable(sub):
    """rekha's rule: horizontal, not minimum, not cross-stream, format 0."""
    if getattr(sub, "format", 0) != 0:
        return False
    cov = sub.coverage
    if getattr(sub, "apple", False):
        return (cov & 0x80) == 0 and (cov & 0x40) == 0
    return (cov & 1) != 0 and (cov & 2) == 0 and (cov & 4) == 0


def expected(font):
    """The accumulated value per (leftGid, rightGid), under rekha's combination rule."""
    gid = {n: i for i, n in enumerate(font.getGlyphOrder())}
    total, napplicable = {}, 0
    for sub in font["kern"].kernTables:
        if not applicable(sub):
            continue
        napplicable += 1
        override = (not getattr(sub, "apple", False)) and (sub.coverage & 8) != 0
        for (a, b), v in sub.kernTable.items():
            if a not in gid or b not in gid:
                continue
            k = (gid[a], gid[b])
            total[k] = v if override else total.get(k, 0) + v
    return total, napplicable


def rekha_values(path, pairs):
    src = DUMPER.replace("__FONT__", path).replace("__PAIRS__", os.path.join(OUT, "kern.pairs"))
    open(os.path.join(OUT, "kd.cyr"), "w").write(src)
    blob = struct.pack("<q", len(pairs))
    for a, b in pairs:
        blob += struct.pack("<qq", a, b)
    open(os.path.join(OUT, "kern.pairs"), "wb").write(blob)
    r = subprocess.run(["cyrius", "build", "build/kd.cyr", "build/kd"],
                       cwd=REPO, capture_output=True, text=True)
    if r.returncode != 0:
        print(r.stdout, r.stderr)
        sys.exit("dumper build failed")
    r = subprocess.run([os.path.join(OUT, "kd")], capture_output=True, text=True)
    if r.returncode != 0:
        sys.exit("dumper run failed: " + r.stderr)
    if r.stdout.startswith("NOFONT"):
        return None
    return [int(x) for x in r.stdout.split()]


def main(argv):
    from fontTools.ttLib import TTFont
    os.makedirs(OUT, exist_ok=True)
    dirs = argv[1:] or DIRS
    paths = set()
    for d in dirs:
        for ext in ("ttf", "otf", "ttc"):
            paths |= set(glob.glob(os.path.join(d, "**", "*." + ext), recursive=True))

    fonts, total_pairs, same, mism, absent_ok, absent_bad = 0, 0, 0, 0, 0, 0
    single = 0
    skipped = []
    for p in sorted(paths):
        try:
            f = TTFont(p, fontNumber=0, lazy=True)
            if "kern" not in f:
                continue
            want, napp = expected(f)
            ng = len(f.getGlyphOrder())
            f.close()
        except Exception as e:
            continue
        if not want:
            skipped.append((p, "no applicable subtable"))
            continue
        keys = sorted(want)
        # a sample of pairs that are NOT in the table: the same lefts, with rights that are absent
        absent = []
        seen = set(keys)
        for (a, b) in keys:
            for cand in ((a, b + 1), (b, a)):
                if cand not in seen and len(absent) < ABSENT_SAMPLE:
                    if cand[0] < ng and cand[1] < ng:
                        absent.append(cand)
                        seen.add(cand)
            if len(absent) >= ABSENT_SAMPLE:
                break
        got = rekha_values(p, keys + absent)
        if got is None:
            skipped.append((p, "rekha would not open it"))
            continue
        fonts += 1
        if napp == 1:
            single += 1
        bad = 0
        for i, k in enumerate(keys):
            total_pairs += 1
            if got[i] == want[k]:
                same += 1
            else:
                mism += 1
                bad += 1
                if bad <= 2:
                    print("  MISMATCH %s %s: fontTools %d rekha %d"
                          % (os.path.basename(p), k, want[k], got[i]))
        for j in range(len(absent)):
            if got[len(keys) + j] == 0:
                absent_ok += 1
            else:
                absent_bad += 1
        print("  %-44s %6d pairs, %d applicable subtable(s)%s"
              % (os.path.basename(p), len(keys), napp, "" if bad == 0 else "   <-- MISMATCHES"))

    print("\n%d fonts, %d pairs: %d identical, %d mismatched" % (fonts, total_pairs, same, mism))
    print("%d of %d fonts have a SINGLE applicable subtable (parse against parse, no rule between)"
          % (single, fonts))
    print("absent-pair probes: %d correctly 0, %d wrong" % (absent_ok, absent_bad))
    for p, why in skipped:
        print("skipped %s: %s" % (os.path.basename(p), why))
    return 0 if (mism == 0 and absent_bad == 0 and total_pairs) else 1


if __name__ == "__main__":
    sys.exit(main(sys.argv))
