#!/usr/bin/env python3
"""mac_roman.py — the Macintosh Roman high half, for src/name.cyr and its gate.

A `name` record on platform 1 encoding 0 is Mac OS Roman, not Unicode and not Latin-1: codes
0x00-0x7F are ASCII and 0x80-0xFF are a fixed 128-entry table that rekha has to carry, because
nothing about it is derivable. This script is where that table comes from, so no one transcribes
it by hand.

    python3 scripts/mac_roman.py table            # the Cyrius chunks for src/name.cyr
    python3 scripts/mac_roman.py emit <path>      # programs/mac_roman_vectors.cyr, the gate

⭐ THE SOURCE IS PYTHON'S OWN `mac_roman` CODEC, not a copy of a table from a web page. `emit`
writes the vectors the RUN suite checks rekha's table against, and CI regenerates and compares it —
the same shape as scripts/cff_stdenc.py and scripts/woff2_triplet.py.

⚠ Stored as HEX, one 4-digit code point per entry, 16 entries a chunk. Storing the characters
themselves would put a non-breaking space (0xCA) and a set of curly quotes into a Cyrius source
literal, where they are invisible to a reader and at the mercy of the formatter.
"""
import sys

CHUNK = 16


def table():
    return [ord(bytes([c]).decode("mac_roman")) for c in range(0x80, 0x100)]


def chunks():
    t = table()
    return ["".join("%04X" % cp for cp in t[i:i + CHUNK]) for i in range(0, len(t), CHUNK)]


def cmd_table():
    cs = chunks()
    print("# GENERATED by scripts/mac_roman.py table — do not edit by hand.")
    print("# Mac OS Roman 0x80..0xFF as code points, %d to a chunk, four hex digits each."
          % CHUNK)
    print("fn rekha_mr_chunk(k): i64 {")
    for i, c in enumerate(cs):
        print('    if (k == %d) { return "%s"; }' % (i, c))
    print('    return "";')
    print("}")


def cmd_emit(path):
    t = table()
    out = []
    out.append("# GENERATED by scripts/mac_roman.py — do not edit by hand.")
    out.append("#")
    out.append("# The Macintosh Roman high half, 0x80..0xFF, as (code, code point) pairs taken from")
    out.append("# Python's own `mac_roman` codec and from nothing in rekha. programs/name_test.cyr")
    out.append("# drives rekha's decoder with these, so a transcription slip in src/name.cyr's")
    out.append("# chunks shows up as a failed check rather than as one wrong character in a name.")
    out.append("")
    out.append("var REKHA_MR_VEC_N = %d;" % len(t))
    out.append("")
    out.append("# The expected code point for Mac Roman byte 0x80 + i.")
    out.append("fn rekha_mr_vec(i): i64 {")
    for i, cp in enumerate(t):
        out.append("    if (i == %3d) { return %5d; }   # 0x%02X" % (i, cp, 0x80 + i))
    out.append("    return 0 - 1;")
    out.append("}")
    out.append("")
    open(path, "w").write("\n".join(out))
    print("wrote %s (%d entries)" % (path, len(t)))


def main(argv):
    if len(argv) >= 2 and argv[1] == "table":
        cmd_table()
        return 0
    if len(argv) >= 3 and argv[1] == "emit":
        cmd_emit(argv[2])
        return 0
    print(__doc__)
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv))
